docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client.Tests/Extensions/ServiceCollectionExtensions.cs
source/ProcessManager.Client.Tests/Fixtures/ProcessManagerClientFixture.cs
source/ProcessManager.Client.Tests/Integration/BRS_023_027/V1/MonitorCalculationUsingClientsScenario.cs
source/ProcessManager.Client.Tests/Integration/BRS_026_028/V1/RequestCalculatedEnergyTimeSeriesTests.cs
source/ProcessManager.Client.Tests/ProcessManager.Client.Tests.csproj
source/ProcessManager.Client/Extensions/DependencyInjection/ClientExtensions.cs
source/ProcessManager.Client/Extensions/Options/ProcessManagerServiceBusClientOptions.cs
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Client/ProcessManagerMessageClient.cs
source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
source/ProcessManager.Orchestrations/Extensions/DependencyInjection/ProcessManagerTopicExtensions.cs
source/ProcessManager.Orchestrations/Extensions/Options/ProcessManagerTopicOptions.cs
source/ProcessManager.Orchestrations/Program.cs
source/ProcessManager.SubsystemTests/ProcessManager.SubsystemTests.csproj
source/ProcessManager.Tests/ProcessManager.Tests.csproj

Add first Service Bus Topic test by testing the `StartRequestCalculatedEnergyTimeSeriesCommandV1`
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/370

test: Add basic client test for StartRequestCalculatedEnergyTimeSeriesCommandV1

---

.github/workflows/cd.yml
.github/workflows/ci-dotnet-runtests.yml
.github/workflows/ci-dotnet.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/detect-changes.yml
global.json
source/ProcessManager.Abstractions/Api/Model/OrchestrationDescription/OrchestrationDescriptionUniqueNameDto.cs

This pull request includes several changes to update the Ubuntu version used in GitHub Actions workflows and to modify the .NET SDK version in the `global.json` file.
Use ubuntu-latest for everything but building artifacts
Use ubuntu-24.04 for building artifacts
* [`global.json`](diffhunk://#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfL3-R3): Changed the .NET SDK version from `8.0.300` to `8.0.100`.

Run dotnet build on ubuntu-24.04 using .NET 8, featureband 8.0.100

---

.github/workflows/ci-dotnet.yml
source/ProcessManager.Orchestrations/Program.cs

This pull request includes changes to the CI workflow configuration and a minor comment correction in the `ProcessManager.Orchestrations` project.
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2660
Improvements to CI workflow:
* [`.github/workflows/ci-dotnet.yml`](diffhunk://#diff-9f761b9e8edbe9c2db37b8ef3863ecc6318bc1930386c72585733ae09ae9016fR55): Added a parameter to the `dotnet publish` command to include the source revision ID and SHA of the pull request.
Minor code comment correction made for testing the build

2660: add PR number to dotnet publish

---

.github/workflows/processmanager-client-bundle-publish.yml
docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj

We discovered an issue with NuGet package publishing, which this PR will (hopefully) fix. See an example of the error in this run: https://github.com/Energinet-DataHub/opengeh-process-manager/actions/runs/12598074801/job/35112217672
We have two NuGet package bundles. and currently, if one of them has changes and should be published - the workflow enforces both of them to be published. With this PR we change this so they are only published if they actually have content changes.

refac: Don't force push NuGet packages when building on main

---

.github/workflows/processmanager-client-bundle-publish.yml
docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj

This pull request includes updates to the workflow and therefore also version bumps for the ProcessManager packages. 
The most important changes involve updating the GitHub Actions workflow to handle manual triggers correctly and adding steps to list changed files for better debugging.
Workflow configuration updates:
* Added `BASE_SHA` environment variable to handle manual triggers correctly.
* Updated `tj-actions/changed-files` action from v41 to v45 and included `base_sha` parameter.
* Added steps to list all changed files for `PM.Client` and `PM.Abstractions` for better debugging.

refac: Fix PM Client bundle publish workflow

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteredDataForMeasurementPointRejectedV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteredDataForMeteringPointRejectedV1.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/CreateRejectMessageActivity_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/EnqueueRejectMessageActivity_Brs_021_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Orchestration_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/TestServices/ElectricityMarketViewsStub.cs

The goal of this PR is to add a skeleton implementation that can create and enqueue an RSM-009 in case the validation of an RSM-012 fails. In particular, the following simplifications are made:
- The receiver and receiver role are hard-coded as we currently don't get those from EDI
- The business type is hard-coded as we currently don't get that from EDI either
- All errors are added using a haed-coded, randomly selected error code
- All errors are added only to the `Reason` list as we currently lack the under standing of how to accurately construct an RSM-009
- The names of the fields and structures in the AcknowlegdementV1 are taken directly from the CIM JSON schema as this makes it easier (for now) to tie everything together

feat: Create and enqueue RSM-009 response

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Components/Datahub/ValueObjects/ActorRole.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/AcceptedEnergyObservation.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/EnergyObservation.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/MarketActorRecipient.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteredDataForMeteringPointAcceptedV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/EnqueueActorMessagesActivity_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Orchestration_Brs_021_ForwardMeteredData_V1.cs

This PR will enable the BRS_21_ForwardMeteredData process to send a message to EDI enqueue a RSM-012 for a accepted metered data series.
There is no test included in this PR for now. Testing the activity in use will be testet in an upcoming PR.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/420

feat: PM -> EDI send RSM-012

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/GetMeteringPointMasterDataActivity_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/PerformValidationActivity_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Mapper/MeteringPointMasterDataMapper.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Model/ConnectionState.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteringPointMasterData.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteringPointSubType.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Orchestration_Brs_021_ForwardMeteredData_V1.cs

If the data type from a third-party package changes, then running orchestrations will not be able to hydrate the object if it has changed

fix: avoid return third part type to orchestration

---

source/ProcessManager.Client.Tests/ProcessManager.Client.Tests.csproj
source/ProcessManager.Components.Tests/ProcessManager.Components.Tests.csproj
source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
source/ProcessManager.Example.Orchestrations.Tests/ProcessManager.Example.Orchestrations.Tests.csproj
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
source/ProcessManager.SubsystemTests/ProcessManager.SubsystemTests.csproj
source/ProcessManager.Tests/ProcessManager.Tests.csproj
source/Shared/Tests/FluentAssertionsVersionGuard.cs

This pull request includes the addition of a new file, `FluentAssertionsVersionGuard.cs`, across multiple test projects. This change ensures that the version of FluentAssertions used in the tests does not exceed version 8 due to licensing constraints.
Key changes include:
* Added the new file `FluentAssertionsVersionGuard.cs` with a test to ensure the version of FluentAssertions does not exceed version 8.
* Added `FluentAssertionsVersionGuard.cs` to multiple test project files to ensure compliance with FluentAssertions' licensing model:
* `source/ProcessManager.Client.Tests/ProcessManager.Client.Tests.csproj`
* `source/ProcessManager.Components.Tests/ProcessManager.Components.Tests.csproj`
* `source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj`
* …

test: Block fluentassertions v8

---

docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/Contracts/EnqueueActorMessagesV1.cs
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Components/EnqueueActorMessages/EnqueueActorMessagesClient.cs
source/ProcessManager.Example.Orchestrations.Tests/Fixtures/ExampleConsumerAppManager.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_026_028/BRS_026/V1/Model/RequestCalculatedEnergyTimeSeriesAcceptedV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_026_028/BRS_026/V1/Model/RequestCalculatedEnergyTimeSeriesRejectedV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_026_028/BRS_028/V1/Model/RequestCalculatedWholesaleServicesAcceptedV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_026_028/BRS_028/V1/Model/RequestCalculatedWholesaleServicesRejectedV1.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/Extensions/ServiceBusReceivedMessageExtensions.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_023_027/V1/ServiceBusResponseMocking.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026_028/BRS_026/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026_028/BRS_028/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Activities/EnqueueActorMessagesActivity_Brs_026_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Activities/EnqueueRejectMessageActivity_Brs_026_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Orchestration_Brs_026_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Activities/EnqueueActorMessagesActivity_Brs_028_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Activities/EnqueueRejectMessageActivity_Brs_028_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Orchestration_Brs_028_V1.cs
source/Shared/Tests/Fixtures/Extensions/ProcessManagerClientExtensions.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

This pull request includes updates to the `ProcessManager.Orchestrations.Abstractions` package, focusing on adding missing properties to certain request models, updating the package version, and enhancing test scenarios for orchestration processes. The most important changes are summarized below:
* Added missing properties to `RequestCalculatedEnergyTimeSeriesRejectedV1` and `RequestCalculatedWholesaleServicesRejectedV1` models. [[1]](diffhunk://#diff-4cf4c34e84b6a312de9ecfec1739c8257021145e1d8f942c0d23e2ee50b329f3R16-R30) [[2]](diffhunk://#diff-d53ee1c35234459075038ffc6064e6784c6ddef73b9ba5b8c7beb52ef84aa1dcR16-R30)
* Updated the package version to `0.18.2` in the `ProcessManager.Orchestrations.Abstractions.csproj` file.
* Added a new extension method `TryParseAsEnqueueActorMessages` to …

feat: Update BRS-026 and BRS-028 rejected data types

---

source/ProcessManager.DatabaseMigration/DbUpgrader.cs
source/ProcessManager.DatabaseMigration/Scripts/202501311000 Add RowVersion.sql

Make script idempotent.
This change is necessary because the script alters two different tables, and when DbUp runs the script it is possible that the first table was altered, but the second was not. In this case DbUp has not updated its journal over executed scripts and doesn't know that it has executed part of the script with success. So the script must be idempotent and be able to be executed again without failing.
Deployed to `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13109549441
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/499

refac: Update script so it only add column if it was not added already

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026_028/BRS_026/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026_028/BRS_028/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Orchestration_Brs_026_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Steps/BusinessValidationStep.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Steps/EnqueueActorMessagesStep.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Orchestration_Brs_028_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Steps/BusinessValidationStep.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Steps/EnqueueActorMessagesStep.cs
source/Shared/Tests/Fixtures/Extensions/ProcessManagerClientExtensions.cs

- Refactor BRS-026 and BRS-028 to use the new steps with `StepExecutor` base, to help handle step lifecycle transitions and exception handling.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/512
This pull request includes several changes to the orchestration process for BRS_026 and BRS_028. The changes focus on refactoring the orchestration steps, improving code readability, and updating test scenarios to reflect the new structure.
* [`source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Orchestration_Brs_026_V1.cs`](diffhunk://#diff-02e5296e585bd469383ee44b00e4803bd757b4f92efd71c76ed8b85ad26765c8L18-R39): Replaced individual step methods with new `BusinessValidationStep` and …

feat: Update BRS-026 and 028 to handle errors by using step executor

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Core.Tests/Integration/Infrastructure/Orchestration/OrchestrationInstanceRepositoryTests.cs
source/ProcessManager.Core/Application/Orchestration/IOrchestrationInstanceQueries.cs
source/ProcessManager.Core/Infrastructure/Orchestration/OrchestrationInstanceRepository.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_026_028/CustomQueries/ActorRequestQuery.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026_028/CustomQueries/SearchTrigger_Brs_026_028Tests.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/CustomQueries/SearchActorRequestHandler.cs

- Add `createdByActorId` to `ActorRequestQuery`
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/489

feat: Add created by actor filter to actor request query

---

source/ProcessManager.Orchestrations.Tests/Unit/Extensions/DependencyInjection/MeasurementsMeteredDataClientExtensionsTests.cs
source/ProcessManager.Orchestrations/Extensions/DependencyInjection/MeasurementsMeteredDataClientExtensions.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/Options/MeasurementsMeteredDataClientOptions.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

Small "cleanup" moving `MeasurementsMeteredDataClientOptions` out of `Components` and into `Orchestrations` which is the only one using it. 

refac: Move MeasurementsMeteredDataClientOptions

---

source/ProcessManager.Orchestrations/Processes/BRS_023_027/CustomQueries/SearchCalculationHandler.cs

The query is now equal to the old query in Wholesale. See https://stackoverflow.com/questions/13513932/algorithm-to-detect-overlapping-periods for explanation about the `bool overlap = a.start < b.end && b.start < a.end` algorithm.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/563

fix: Fix period overlap check in calculations query

---

source/ProcessManager.Core.Tests/Integration/Application/Orchestration/INotifyOrchestrationInstanceCommandsTests.cs
source/ProcessManager.Core/Application/Orchestration/OrchestrationInstanceManager.cs

Update `INotifyOrchestrationInstanceCommands` to handle non-durable function orchestrations.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/550
- d002 deploy: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13564487189

feat: Handle non-df in `NotifyOrchestrationInstanceAsync`

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsMeteredDataClientTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/Contracts/Brs021ForwardMeteredDataNotifyV1.proto
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/Contracts/Brs021ForwardMeteredDataNotifyVersion.proto
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsMeteredDataClient.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/EnqueMeteredDataTrigger_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/StartTrigger_Brs_021_ForwardMeteredData_V1.cs

Re-introduce the happy path test of brs021-forwardMeteredData and update the notification contract from measurements with a version field. 
The version field will determine which version of the contract we can use to deserialize the event from measurements when we communicate via Event Hub. 

feat: full happy part of brs021

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs

Re-enable the call to Electricity market to get the metering point master data. 

fix: re-enable get metering point master data

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/TerminateForwardMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Model/EnqueueActorMessagesStepCustomStateV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/OrchestrationDescriptionBuilderV1.cs

- Use the same idempotency key for enqueuing BRS-021 messages
- Refactor `EnqueueMeteredDataHandlerV1` to align idempotency/retry logic

feat: Use the same idempotency key for BRS-021 enqueue actor messages, even if retrying

---

source/ProcessManager.Orchestrations/Extensions/DependencyInjection/ProcessManagerTopicExtensions.cs

Adding health checks on service bus topics and subscriptions related to brs021_forwardMeteredData

feat: added health checks on start and notify brs021_forward topics and subscription

---

source/ProcessManager.Core/Application/FeatureFlags/FeatureFlag.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/ForwardMeteredDataBusinessValidatedDtoValidatorTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointValidationRuleTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointValidationRule.cs

To test the reject flow where we enqueue an RSM009 document. MeteringPoint business validation rule is enabled behind a feature flag:
- UseBrs021ForwardMeteredDataBusinessValidationForMeteringPoint
If the feature is enabled, missing master data for a metering point triggers the reject flow.
Infra PR: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/3225

feat: return business validation error when no master data for metering point

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProviderTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProvider.cs

This pull request focuses on updating the unit tests for the `MeteringPointMasterDataProvider` class in the `ProcessManager.Orchestrations` project. The changes include renaming test methods for clarity, modifying test logic to check for different outcomes, and removing obsolete tests.
Key changes include:
* Renamed and updated the test method `Given_MasterDataWithNoEnergySuppliers_When_GetMasterData_Then_Error` to `Given_MasterDataWithNoEnergySuppliers_When_GetMasterData_Then_NoMasterData` and changed the logic to check for an empty result instead of throwing an exception.
* Renamed and updated the test method `Given_TwoMasterDataWithOneFaultyEnergySuppliers_When_GetMasterData_Then_Error` to `Given_TwoMasterDataWithOneFaultyEnergySuppliers_When_GetMasterData_Then_NonFaultMasterDataReturne …

feat: Remove master data validation

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/ForwardMeteredDataBusinessValidatedDtoValidatorTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointOwnershipValidationRuleTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointOwnershipValidationRule.cs

Ensure that the grid area owner in the input is in fact the grid area owner according to the relevant metering point master data.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/437

feat: Add metering point ownership validation

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/Extensions/InstantPatternWithOptionalSecondsTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Extensions/InstantPatternWithOptionalSeconds.cs

Fix: None of the specified formats matches the given value string. Value being parsed: '^2025-03-17T11:13:48.1955802Z'. (^ indicates error position.)
When Process Manager parses the string representation of a date.

fix: issue with instant parsing for ebix with fractional seconds

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProviderTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProvider.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointReceiversProvider.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteringPointMasterData.cs

It is a valid and plausible scenario, that a metering point, for a brief period, does not have an attached energy supplier. In this case we must still validate the master data and continue the flow as usual, with the implicit change, that we do not forward the metered data to any energy supplier in this period.
This pull request includes several changes to the `MeteringPointMasterDataProviderTests` and related classes to improve the handling of energy supplier data and ensure null checks are properly implemented. The most important changes include updating test assertions, modifying methods to handle cases with no energy suppliers, and adding null checks before accessing energy supplier properties.
* Updated assertions in `MeteringPointMasterDataProviderTests` to check for null values and …

feat: Allow master data to have no energy suppliers

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs

Changed recurring trigger time for the orchestrations:
- Electrical Heating
- Net Consumption
- Missing Measurements Log
The new times are described here:
https://energinet.atlassian.net/wiki/spaces/D3/pages/1459224683/Process+Manager
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/634

feat: Changed recurring trigger time for some orchestrations

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/PositionCountValidationRuleTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/PositionCountValidationRule.cs

Ensure we can handle periods where start and end data are set to the end of the month. 

fix: position count validation rule when res is P1M and period is end of month

---

source/ProcessManager.Components/ProcessManager.Components.csproj
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProviderTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointTypeValidationRuleTests.cs
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/ElectricityMarket/MeteringPointMasterDataProvider.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Mapper/MeteringPointMasterDataMapper.cs

- Switched to ElectricityMarket Integration 4.0.5
- Rewrote `GetMasterData` to support normalised data which is returned from `ElectricityMarket`  when getting `MeteringPointMasterData`.
- `GetMasterData` now supports adding slices for parents periods within a childs period. (Written with help from ChatGTP)
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/658

feat: support for normalised MeteringPointMasterData 

---

source/ProcessManager.Orchestrations.Tests/Fixtures/OrchestrationsAppFixture.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

This PR updates the test setup to use a new event hub namespace configuration for integration tests. The changes update environment variable references and add a new property in the OrchestrationsAppManager to support the new event hub namespace until TestCommon is updated.

test: Use new event hub for tests

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/ForwardMeteredDataBusinessValidatedDtoValidatorTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointSubTypeValidationRuleTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointSubTypeValidationRule.cs

A new validation rule was added to ensure master data for the metering point has the correct metering point subtype.

feat: metering point sub type  validation rule for brs021-ForwardMeteredData

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs

If no `QuantityQuality` is provided, it is expected to be sent forward as `AsProvided`.

refac: if QuantityQuality is null, set to AsProvided

---

source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/StartTrigger_Brs_026_V1.cs
source/ProcessManager.SubsystemTests/Processes/BRS_026_028/BRS_026/V1/RequestCalculatedEnergyTimeSeriesScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_026_028/BRS_028/V1/RequestCalculatedWholesaleServicesScenario.cs

This PR updates two subsystem tests to wait for the orchestration instance to be running rather than queued before proceeding.
- Renames test methods from When_OrchestrationInstanceIsStarted to When_OrchestrationInstanceIsRunning.
- Updates the orchestration state check from Queued to Running in the WaitForOrchestrationInstanceAsync calls and corresponding assertions.

test: Update subsystem tests to wait for orchestration to be running

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/TerminateForwardMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/StepHelper.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/EnqueueMeteredDataTrigger_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/StartTrigger_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/TerminateTrigger_Brs_021_ForwardMeteredData_V1.cs

Added metrics to track performance for executing Brs021-forward:
- Metrics added for each function, automatically tracking values such as request count, duration, and failure rate.
- Metrics also track the duration between when a step is started and when it is terminated.

feat: added metric in brs021-forward process

---

source/ProcessManager.Orchestrations/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs

Changed missing measurement logs activation time.
Now it runs at 2AM on weeksday.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/706

refac: Changed missing measurement logs activation time

---

source/ProcessManager.Components/MeteringPointMasterData/MeteringPointMasterDataProvider.cs
source/ProcessManager.Core.Tests/Unit/Application/Handlers/StartOrchestrationInstanceFromMessageHandlerTests.cs
source/ProcessManager.Core/Application/Api/Handlers/StartOrchestrationInstanceFromMessageHandler.cs

In StartOrchestrationInstanceFromMessageHandler, we throw an ArgumentOutOfRangeException after handling a ServiceBusReceivedMessage for all received messages, even when the message contains a valid MajorVersion.

fix: avoid throwing ex when start orch insta message is handled

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Components/Time/TimeHelper.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/Model/CalculationInputV1.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_045/MissingMeasurementLogsCalculation/V1/Activities/CalculationStep/CalculationStepStartJobActivity_Brs_045_MissingMeasurementsLogCalculation_V1.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/Activities/CalculationStep/CalculationStepStartJobActivityBrs045MissingMsLogCalOnDemandV1Tests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/Activities/CalculationStep/CalculationStepStartJobActivity_Brs_045_MissingMeasurementsLogCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/Activities/CalculationStep/CalculationStepStartJobActivity_Brs_045_MissingMeasurementsLogOnDemandCalculation_V1.cs

Added grid area codes to missing measurements log on demand. They were missing.
https://github.com/Energinet-DataHub/opengeh-process-manager/pull/400

fix: Added grid area codes to missing measurements log on demand 

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/EnqueueMeteredDataTrigger_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/host.json

The event hub trigger has been refactored to support batching, enabling it to handle the high volume of events for BRS021 more efficiently. Each message will now be processed in its own scope, in parallel, to utilize resources on each instance better.
Right now, we are processing 1 event at a time

feat: brs021 notify eventhub trigger support batches

---

source/ProcessManager.SubsystemTests/Processes/BRS_021/NetConsumptionCalculation/V1/NetConsumptionCalculationScenario.cs

Added basic Net Consumption subsystem test.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/774

test: Added Net Consumption subsystem test

---

source/ProcessManager.Components.Tests/Unit/MeteringPointMasterData/MeteringPointMasterDataProviderTests.cs
source/ProcessManager.Components/EnqueueActorMessages/EdiTopicServiceBusSenderFactory.cs
source/ProcessManager.Components/Extensions/TestMessageIdExtensions.cs
source/ProcessManager.Components/MeteringPointMasterData/ElectricityMarketViewsFactory.cs
source/ProcessManager.Components/MeteringPointMasterData/MeteringPointMasterDataProvider.cs
source/ProcessManager.Orchestrations.Tests/Unit/Extensions/DependencyInjection/MeasurementsClientExtensionsTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClientTests.cs
source/ProcessManager.Orchestrations/Extensions/DependencyInjection/Brs021Extensions.cs
source/ProcessManager.Orchestrations/Extensions/DependencyInjection/MeasurementsClientExtensions.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/IMeasurementsClient.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClient.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsEventHubProducerClientFactory.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeteringPointOwnershipValidationRule.cs
source/ProcessManager.SubsystemTests/Fixtures/Extensions/ProcessManagerFixtureExtensions.cs
source/ProcessManager.SubsystemTests/Fixtures/ProcessManagerFixture.cs
source/ProcessManager.SubsystemTests/Fixtures/ProcessManagerSubsystemTestConfiguration.cs
source/ProcessManager.SubsystemTests/Processes/BRS_021/ElectricalHeatingCalculation/V1/ElectricalHeatingCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_021/NetConsumptionCalculation/V1/NetConsumptionCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_021/SendMeasurements/V1/SendMeasurementsScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_021/SendMeasurements/V1/SendMeasurementsScenarioState.cs
source/ProcessManager.SubsystemTests/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/MissingMeasurementsLogCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_045/MissingMeasurementsLogOnDemand/V1/MissingMeasurementsLogOnDemandCalculationScenario.cs
source/ProcessManager.SubsystemTests/subsystemtest.local.settings.sample.json

- Add BRS-021 Send Measurements subsystem test.
- Mock Electricity Market Views when running subsystem tests.
- Mock Measurements Event Hub producer client when running subsystem tests.
- Fix tests.
- Requires Environments PR: https://github.com/Energinet-DataHub/dh3-environments/pull/1492
- Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/657
- D002 run: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/15250693606/job/42887179794

test: Add BRS-021 Send Measurements subsystem test

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/ForwardMeteredDataInputV1.cs

Extend the input with a DataSource property that we can use from EDI to tell where data originated from.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/808
- `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/15554765858

feat: Extend ForwardMeteredDataInputV1 with DataSource

---

source/ProcessManager.Core/Application/SendMeasurements/ISendMeasurementsInstanceRepository.cs
source/ProcessManager.Core/Domain/SendMeasurements/SendMeasurementsInstance.cs
source/ProcessManager.Core/Infrastructure/Orchestration/SendMeasurementsInstanceRepository.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/ProcessManagerAzuriteCollection.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/ProcessManagerAzuriteFixture.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeasurementsHandlerV1OldTests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeasurementsHandlerV1Tests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1Tests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/ServiceBusResponseMocking.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/ForwardMeteredDataInputV1Builder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Extensions/ForwardMeteredDataInputSerializationExtensions.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeasurementsHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Triggers/EnqueueMeteredDataTrigger_Brs_021_ForwardMeteredData_V1.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

- Update `EnqueueMeasurementsHandlerV1` to use new `SendMeasurementsInstance` (if feature is enabled).
- Copy `EnqueueMeasurementsHandlerV1Tests` to `EnqueueMeasurementsHandlerV1OldTests` (DO NOT REVIEW THIS, it is just a copy of the existing tests).
- Update `EnqueueMeasurementsHandlerV1Tests` to test the new `SendMeasurementsInstance` flow, including adding `Azurite` (File Storage) support.
- Update `StartForwardMeteredDataHandlerV1Tests` to check for correct database & file storage values.
- Remove `OrchestrationDescriptionBuilder.UniqueName` property, since it was just a duplicate of `Brs_021_ForwardedMeteredData.V1`.
- Update `EnqueueMeteredDataTrigger_Brs_021_ForwardMeteredData_V1` to support both `OrchestrationInstanceId` and `SendMeasurementsInstanceId`.
- Link to assignment: …

feat: Update Send Measurements handler to use Send Measurements Instance
