Energinet-DataHub/opengeh-process-manager

source/ProcessManager.DatabaseMigration/ProcessManager.DatabaseMigration.csproj
source/ProcessManager.DatabaseMigration/Scripts/202410240916 Create OrchestrationInstance table.sql
source/ProcessManager.DatabaseMigration/Scripts/202411192300 Add operating identity columns.sql
source/ProcessManager.DatabaseMigration/Scripts/202411211300 Update Lifecycle_CreatedBy_IdentityType.sql

refac: Merge database scripts

---

.github/workflows/cd.yml

feat: Add CD workflow

---

.github/workflows/cd.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/processmanager-client-bundle-publish.yml
docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Client/ProcessManager.Client.csproj

Update .github stuff to version 14

chore: Update .github from 13 to 14

---

docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Core/ProcessManager.Core.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager.Orchestrations/Processes/BRS_023_027/SearchCalculationHandler.cs
source/ProcessManager/ProcessManager.csproj

chore: Nuget update

---

.editorconfig

chore: Update .editorconfig to match EDI

---

source/ProcessManager.sln.DotSettings

chore: Avoid Rider typo complaint about "Energinet"

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/CalculationStepStartActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/CalculationStepTerminateActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/EnqueueMessagesStepStartActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/EnqueueMessagesStepTerminateActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Orchestration_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/StepIdentifierDto.cs
source/ProcessManager.Orchestrations/Program.cs

feat: Make BRS-021 electrical heating registration more generic

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/SchedulerTrigger.cs

feat: Avoid bad identities (disable trigger temporarily)

---

source/ProcessManager.Core/Application/Registration/IOrchestrationRegister.cs
source/ProcessManager.Core/Application/Registration/OrchestrationRegisterExtensions.cs
source/ProcessManager.Core/Domain/OrchestrationDescription/OrchestrationDescription.cs
source/ProcessManager.Core/Infrastructure/Registration/OrchestrationRegister.cs
source/ProcessManager.Orchestrations/Program.cs

Allow certain properties to be update for an existing Orchestration Description.

feat: Support refreshable properties

---

source/ProcessManager.Core/Application/Registration/IOrchestrationDescriptionBuilder.cs
source/ProcessManager.Core/Infrastructure/Extensions/DependencyInjection/ProcessManagerExtensions.cs
source/ProcessManager.Core/Infrastructure/Extensions/Startup/HostExtensions.cs
source/ProcessManager.Example.Orchestrations/Processes/BRS_X01/InputExample/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Example.Orchestrations/Processes/BRS_X01/NoInputExample/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Example.Orchestrations/Program.cs
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_023_027/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_026/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Program.cs

Let's try to avoid business developer changing `Program.cs`
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/460

feat: Auto Register Orchestration Descriptions

---

.github/CODEOWNERS
source/ProcessManager.Components.Tests/Unit/Extensions/DependencyInjection/DatabricksWorkspaceExtensionsTests.cs
source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
source/ProcessManager.Core.Tests/Unit/Infrastructure/Extensions/DependencyInjection/ProcessManagerExtensionsTests.cs
source/ProcessManager.Core/Infrastructure/Extensions/DependencyInjection/ProcessManagerExtensions.cs
source/ProcessManager.Example.Orchestrations/ProcessManager.Example.Orchestrations.csproj
source/ProcessManager.Example.Orchestrations/Program.cs
source/ProcessManager.Orchestrations/Program.cs

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/460

feat: Auto register handlers

---

source/ProcessManager.Components.Tests/ProcessManager.Components.Tests.csproj
source/ProcessManager.Example.Orchestrations.Tests/ProcessManager.Example.Orchestrations.Tests.csproj
source/ProcessManager.Example.Orchestrations/ProcessManager.Example.Orchestrations.csproj
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager/ProcessManager.csproj

chore: Update nuget packages

---

source/ProcessManager.Orchestrations.Tests/Fixtures/Extensions/DatabricksAbstractionExtensions.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/Extensions/DatabricksApiWireMockExtensions.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/OrchestrationsAppFixture.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/OrchestrationsAppManager.cs
source/ProcessManager.Orchestrations.Tests/Integration/Monitor/HealthCheckEndpointTests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ElectricalHeatingCalculation/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_023_027/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/459

test: Mocking databricks job status

---

source/ProcessManager/ProcessManager.csproj

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/460

refac: Remove explicit dependency to Abstractions

---

source/ProcessManager.Core/Domain/OrchestrationDescription/OrchestrationDescription.cs
source/ProcessManager.Core/Infrastructure/Registration/OrchestrationRegister.cs

Temporary enable changing `FunctionName ` for existing orchestration descriptions.

feat: Enable changing function name on existing description

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/Shared/BRS_026_028/ActorRequestQuery.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/Shared/BRS_026_028/IActorRequestQueryResult.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/Shared/BRS_026_028/RequestCalculatedEnergyTimeSeriesResult.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/Shared/BRS_026_028/RequestCalculatedWholesaleServicesResult.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/Shared/BRS_026_028/SearchTrigger_Brs_026_028Tests.cs
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager.Orchestrations/Processes/Shared/BRS_026_028/SearchActorRequestHandler.cs
source/ProcessManager.Orchestrations/Processes/Shared/BRS_026_028/SearchTrigger_Brs_026_028.cs

Move shared types used for custom queries
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/421

refac: Move shared types used for custom queries

---

docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/Api/Model/GetOrchestrationInstanceByIdempotencyKeyQuery.cs
source/ProcessManager.Abstractions/Api/Model/IOrchestrationInstanceTypedDto.cs
source/ProcessManager.Abstractions/Api/Model/OrchestrationInstance/OrchestrationInstanceDto.cs
source/ProcessManager.Abstractions/Api/Model/OrchestrationInstanceTypedDto.cs
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/IProcessManagerClient.cs
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Client/ProcessManagerClient.cs
source/ProcessManager.Core/Application/Api/Handlers/StartOrchestrationInstanceFromMessageHandlerBase.cs
source/ProcessManager.Core/Application/Orchestration/IOrchestrationInstanceQueries.cs
source/ProcessManager.Core/Application/Orchestration/OrchestrationInstanceManager.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Tests/Extensions/ProcessManagerClientExtensions.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_026/V1/RequestCalculatedEnergyTimeSeriesTests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_028/V1/RequestCalculatedWholesaleServicesTests.cs
source/ProcessManager.Tests/Unit/Api/Mappers/OrchestrationInstanceMapperExtensionsTests.cs
source/ProcessManager/Api/GetOrchestrationInstanceByIdempotencyKeyTrigger.cs
source/Shared/Api/Mappers/OrchestrationInstanceMapperExtensions.cs
source/Shared/Extensions/ServiceBusMessageExtensions.cs

This PR makes it possible to query data based on `IdempotencyKey`.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/474

feat: IdempotencyKey query

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/Components/Datahub/ValueObjects/BusinessReason.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/MeteredDataForMeteringPointRejectedV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/CreateRejectMessageActivity_Brs_021_ForwardMeteredData_V1.cs

feat: updated MeteredDataForMeteringPointRejectedV1 to use DataHubTypes

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Orchestration_Brs_021_ForwardMeteredData_V1.cs

feat: terminate orchestration when async validation fails

---

source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Orchestration_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Program.cs

fix: missing connection string to electricity market

---

source/ProcessManager.Orchestrations/host.json

test: increase maxConcurrentOrchestratorFunctions 50

---

source/ProcessManager.Orchestrations/host.json

test: increase maxConcurrentCalls fra 16 to 32

---

source/ProcessManager.Orchestrations/host.json

test: increase maxConcurrentCalls fra 32 to 80

---

source/ProcessManager.Core/Application/FeatureFlags/FeatureFlag.cs

fix: cd pipeline

---

source/ProcessManager.Orchestrations/host.json

chore: rollback host json after perf test

---

docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj

This PR fixes NuGet packages since they have not been updated for the repository `opengeh-process-manager`.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/495

refac: Fix csproj files for NuGet packages

---

.github/workflows/processmanager-client-bundle-publish.yml
docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Components.Abstractions/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager/Development.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Components.Abstractions/ProcessManager.Components.Abstractions.csproj
source/ProcessManager.Components/ProcessManager.Components.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj

Removed PM.Components direct dependency to PM.Abstractions and made it transient by adding PM.Abstractions to PM.Components.Abstractions.
Also updated versions, release notes and documentation.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/495

refac: Refactor NuGet dependencies and build

---

docs/ProcessManager.Components.Abstractions/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Components.Abstractions/ProcessManager.Components.Abstractions.csproj
source/ProcessManager.Components.Abstractions/ValueObjects/DataHubRecordType.cs
source/ProcessManager.Components.Tests/Unit/ValueObjects/SettlementMethodTests.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj

Extend `DataHubRecordType<TDataHubRecordType>` with method `FromNameOrDefault`.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/495

refac: Extend with FromNameOrDefault

---

source/ProcessManager.Components/BusinessValidation/GridAreaOwner/ElectricityMarketGridAreaOwnerClient.cs
source/ProcessManager.Components/BusinessValidation/GridAreaOwner/GridAreaOwnerClient.cs
source/ProcessManager.Components/BusinessValidation/GridAreaOwner/IGridAreaOwnerClient.cs
source/ProcessManager.Components/Extensions/DependencyInjection/BusinessValidationExtensions.cs
source/ProcessManager.Components/ProcessManager.Components.csproj
source/ProcessManager.Core/ProcessManager.Core.csproj
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_026_028/BRS_026/V1/BusinessValidation/RequestCalculatedEnergyTimeSeriesInputV1ValidatorTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_026_028/BRS_028/V1/BusinessValidation/RequestCalculatedWholesaleServicesInputV1ValidatorTests.cs
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Activities/GetMeteringPointMasterDataActivity_Brs_021_ForwardMeteredData_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Mapper/MeteringPointMasterDataMapper.cs
source/ProcessManager.Orchestrations/TestServices/ElectricityMarketViewsStub.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

- Update Electricity Market NuGet package and fix breaking changes
- Use Electricity Market client to get grid area owner
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/496
Infrastructure PR:
- https://github.com/Energinet-DataHub/dh3-infrastructure/pull/2934

feat: Use Electricity Market client for grid area owner

---

source/ProcessManager.Orchestrations/Processes/BRS_023_027/V1/Orchestration_Brs_023_027_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_026/V1/Orchestration_Brs_026_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_026_028/BRS_028/V1/Orchestration_Brs_028_V1.cs

feat: Increase retry policy to 1 hour (from 7,5 minutes)

---

source/ProcessManager.Components/BusinessValidation/GridAreaOwner/ElectricityMarketGridAreaOwnerClient.cs

fix: Mitigate get grid area owner http request exception

---

source/ProcessManager.DatabaseMigration/ProcessManager.DatabaseMigration.csproj
source/ProcessManager.DatabaseMigration/Scripts/202502211500 Add on delete cascade.sql

refac: ON DELETE CASCADE

---

docs/ProcessManager/Development.md

Add markdown documentation for the `SilentMode` feature flag.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/538

doc: Add silent mode feature flag md documentation

---

source/ProcessManager.Core.Tests/Integration/Application/Orchestration/IStartOrchestrationInstanceCommandsTests.cs
source/ProcessManager.Core/Application/Orchestration/OrchestrationInstanceManager.cs
source/ProcessManager.Core/Domain/OrchestrationDescription/OrchestrationDescription.cs
source/ProcessManager.Core/Infrastructure/Database/OrchestrationDescriptionEntityConfiguration.cs
source/ProcessManager.DatabaseMigration/ProcessManager.DatabaseMigration.csproj
source/ProcessManager.DatabaseMigration/Scripts/202502261006 Add IsDurableFunction to OrchestrationDescription.sql

https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/550

feat: Add `IsDurableFunction` to `OrchestrationDescription`

---

source/ProcessManager.Core.Tests/Integration/Application/Orchestration/IStartOrchestrationInstanceCommandsTests.cs
source/ProcessManager.Core.Tests/Integration/Application/Orchestration/IStartOrchestrationInstanceMessageCommandsTests.cs
source/ProcessManager.Core/Domain/OrchestrationDescription/OrchestrationDescription.cs
source/ProcessManager.Core/Infrastructure/Database/OrchestrationDescriptionEntityConfiguration.cs
source/ProcessManager.DatabaseMigration/ProcessManager.DatabaseMigration.csproj
source/ProcessManager.DatabaseMigration/Scripts/202502270811 Remove IsDurableFunction from OrchestrationDescription.sql

Derive the value `IsDurableFunction` from the `FunctionName` property on the `OrchestrationDescription`.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/550
- d002 deploy: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13562269807

feat: Derive `IsDurableFunction` from `FunctionName`

---

source/ProcessManager.Orchestrations.Tests/Fixtures/ProcessManagerDatabaseFixture.cs
source/ProcessManager.Orchestrations.Tests/Integration/InternalProcesses/MigrateCalculationsFromWholesale/Wholesale/WholesaleContextTests.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_023_027/V1/CustomQueries/SearchCalculationHandlerTests.cs

test: Add search calculation handler period tests

---

source/ProcessManager.Example.Orchestrations.Tests/Fixtures/ExampleConsumerAppManager.cs
source/Shared/Tests/Fixtures/ExampleOrchestrationsAppManager.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs
source/Shared/Tests/Fixtures/ProcessManagerAppManager.cs

1: Avoid extensive logging from EF Core in tests
Example of logging that is not seen anymore:
2: Avoid extensive logging from Azure Storage in tests:
Example of logging that is not seen anymore:

feat: Update app managers to reduce logging during tests

---

source/ProcessManager.Client.Tests/Integration/Authorization/AuthorizationHeaderProviderTests.cs
source/ProcessManager.Components/ProcessManager.Components.csproj
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_026_028/BRS_028/V1/BusinessValidation/RequestCalculatedWholesaleServicesInputV1ValidatorTests.cs
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj
source/Shared/Tests/Fixtures/ExampleOrchestrationsAppManager.cs
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

feat: Update to Electricity Market package version with token authentication

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/OrchestrationDescriptionBuilder.cs

The process is planned to be activated at 12:00 and 17:00.
Enabled only for test01 and dev002 via infrastructure settings.
[Link to assignment:](https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/657)

feat: Enabled Electrical Heating process

---

docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Components.Abstractions/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/Api/Model/IOrchestrationInstanceTypedDto.cs
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Components.Abstractions/ProcessManager.Components.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/InternalProcesses/MigrateCalculationsFromWholesale/V1/MigrateCalculationsFromWholesaleCustomStateV1.cs
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Tests/Integration/InternalProcesses/MigrateCalculationsFromWholesale/V1/Activities/ValidateMigratedCalculationsActivityTests.cs
source/ProcessManager.Orchestrations/InternalProcesses/MigrateCalculationsFromWholesale/V1/Activities/GetCalculationsToMigrateActivity_MigrateCalculationsFromWholesale_V1.cs
source/ProcessManager.Orchestrations/InternalProcesses/MigrateCalculationsFromWholesale/V1/Activities/MigrateCalculationActivity_MigrateCalculationsFromWholesale_V1.cs
source/ProcessManager.Orchestrations/InternalProcesses/MigrateCalculationsFromWholesale/V1/Activities/ValidateMigratedCalculationsActivity_MigrateCalculationsFromWholesale_V1.cs
source/ProcessManager.Orchestrations/InternalProcesses/MigrateCalculationsFromWholesale/Wholesale/ProcessManagerContextExtensions.cs
source/ProcessManager.Orchestrations/Processes/BRS_023_027/V1/Activities/GetOrchestrationInstanceContextActivity_Brs_023_027_V1.cs

feat: Expose custom state on orchestration instance interface

---

source/ProcessManager.Core/Infrastructure/Extensions/Options/ProcessManagerOptions.cs
source/ProcessManager.Orchestrations.Tests/Integration/Monitor/HealthCheckEndpointTests.cs

chore: disallow breaking changes in orchestration descriptions

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/CapacitySettlementCalculation/V1/Model/StartCalculationCommandV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/ForwardMeteredDataCommandV1.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/NetConsumptionCalculation/Brs_021_NetConsumptionCalculation.cs
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/NetConsumptionCalculation/V1/Model/StartNetConsumptionCalculationCommandV1.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/NetConsumptionCalculation/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/GetOrchestrationInstanceContextActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Model/OrchestrationInstanceContext.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Activities/CalculationStep/CalculationStepGetJobRunStatusActivity_Brs_021_NetConsumptionCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Activities/CalculationStep/CalculationStepStartJobActivity_Brs_021_NetConsumptionCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Activities/GetOrchestrationInstanceContextActivity_Brs_021_NetConsumptionCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Model/OrchestrationInstanceContext.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Options/OrchestrationOptions_Brs_021_NetConsumptionCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Orchestration_Brs_021_NetConsumptionCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Steps/CalculationStep.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Steps/EnqueueActorMessagesStep.cs

Added a new reoccurring process for net consumption (group 6).
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/679

feat: Added net consumption process

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs

We have disabled the call to Electricity market for now. 

fix: issue with getting master data from electricity market

---

source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeteredDataHandlerV1.cs

fix: Fix enqueue BRS-021 forward metered data

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/ForwardMeteredDataRejectedV1.cs

chore: Rename Original business reason

---

source/ProcessManager.Example.Orchestrations/Processes/BRS_101/UpdateMeteringPointConnectionState/V1/StartTrigger_Brs_101_UpdateMeteringPointConnectionState_V1.cs
source/ProcessManager.Example.Orchestrations/Processes/BRS_101/UpdateMeteringPointConnectionState/V1/StartUpdateMeteringPointConnectionStateV1.cs

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/596

refac: Fix name of start handler

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/StartCalculationHandlerV1Tests.cs

Skip failing unit test for BRS-045

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/StartCalculationHandlerV1Tests.cs

A failing test in StartCalculationHandlerV1Tests.cs fixed.

fix: Due to summer time transition a test failed

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/ForwardMeteredDataRejectedV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/StartForwardMeteredDataHandlerV1.cs

feat: Update actor Identity for forward metered data

---

source/ProcessManager.Components/ProcessManager.Components.csproj
source/ProcessManager.Orchestrations/ProcessManager.Orchestrations.csproj

fix: not aligned metering point types enum values (brs021)

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/Measurements/Mappers/MeteredDataToMeasurementMapperTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/Contracts/PersistSubmittedTransaction.proto
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/Mappers/MeteredDataToMeasurementMapper.cs

fix: added missing monthly resolution in PersistSubmittedTransaction proto

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_021/ForwardMeteredData/V1/Model/ForwardMeteredDataAcceptedV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/Handlers/EnqueueMeteredDataHandlerV1.cs

Added grid area code to ForwardMeteredDataAcceptedV1, which can be used to look up delegation in EDI

feat: added grid area code to ForwardMeteredDataAcceptedV1

---

source/ProcessManager.Client.Tests/ProcessManager.Client.Tests.csproj
source/ProcessManager.Components.Tests/ProcessManager.Components.Tests.csproj
source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
source/ProcessManager.Example.Orchestrations.Tests/ProcessManager.Example.Orchestrations.Tests.csproj
source/ProcessManager.Orchestrations.Tests/Fixtures/OrchestrationsAppFixture.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ForwardMeteredData/V1/MonitorOrchestrationUsingClientsScenario.cs
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
source/ProcessManager.SubsystemTests/ProcessManager.SubsystemTests.csproj
source/ProcessManager.Tests/ProcessManager.Tests.csproj
source/Shared/Tests/Fixtures/OrchestrationsAppManager.cs

chore: Use Event Hub namespace from updated TestCommon version

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/ForwardMeteredDataBusinessValidatedDtoValidatorTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeasureDataQualityValidationRuleTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/MeteringPointMasterDataBuilder.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/Shared/ElectricityMarket/MeteringPointReceiversProviderTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/MeasureDataQualityValidationRule.cs

- Add `MeasureDataQualityValidationRule` with tests.
- Refactor `ForwardMeteredDataBusinessValidatedDtoValidatorTests` by introducing a `MeteringPointMasterDataBuilder`.
* Replaced direct instantiation of `MeteringPointMasterData` with the new `MeteringPointMasterDataBuilder` across multiple test cases to streamline the creation of test data. [[1]](diffhunk://#diff-8bf9c58f26cbdd0751e6f476623cd4d5f6a6d4be69b6061f76ef5222a8cabc14L74-R78) [[2]](diffhunk://#diff-8bf9c58f26cbdd0751e6f476623cd4d5f6a6d4be69b6061f76ef5222a8cabc14L107-R101) [[3]](diffhunk://#diff-8bf9c58f26cbdd0751e6f476623cd4d5f6a6d4be69b6061f76ef5222a8cabc14L159-R143) [[4]](diffhunk://#diff-8bf9c58f26cbdd0751e6f476623cd4d5f6a6d4be69b6061f76ef5222a8cabc14L193-R168) [[5]](diffhunk://#diff-8bf9c58f26cbdd0751e6f476623cd4d5f6a6d4be69 …

feat: Add measure data quality validation for Forward Metered Data

---

.github/workflows/ci-dotnet.yml

build: Fix cache restore key

---

source/ProcessManager.Orchestrations.Tests/Fixtures/Extensions/ElectricityMarketViewsWireMockExtensions.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/ElectricalHeatingCalculation/V1/MonitorOrchestrationUsingClientsScenario.cs

- Add Electricity Market master data mock using `WireMock`
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/688

test: Add Electricity Market master data mock

---

source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/QuantityValidationRuleTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/V1/BusinessValidation/QuantityValidationRule.cs

Feat: Quantity validation rule

---

source/ProcessManager.Orchestrations.Tests/Fixtures/CalculatedMeasurementsQueryFixture.cs
source/ProcessManager.Orchestrations.Tests/Fixtures/Extensions/DatabricksSqlStatementApiCalculatedMeasurementsExtensions.cs
source/ProcessManager.Orchestrations.Tests/Integration/Processes/BRS_021/Shared/Databricks/SqlStatements/CalculatedMeasurementsQueryTests.cs
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Activities/EnqueueActorMessagesStep/EnqueueActorMessageActivity_Brs_021_ElectricalHeatingCalculation_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Orchestration/Steps/EnqueueActorMessagesStep.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/Databricks/SqlStatements/CalculatedMeasurementsColumnNames.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/Databricks/SqlStatements/CalculatedMeasurementsQuery.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/Databricks/SqlStatements/CalculatedMeasurementsSchemaDescription.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/Databricks/SqlStatements/Model/CalculatedMeasurement.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/Databricks/SqlStatements/Model/MeasureData.cs

Move Databricks to a shared folder. Delete notes.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/634

refac: Move Databricks to shared folder

---

source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/ElectricityMarket/MeteringPointMasterDataProvider.cs

fix: use correct message id check to mock EM response

---

source/ProcessManager.Orchestrations/Processes/BRS_021/Shared/ElectricityMarket/MeteringPointMasterDataProvider.cs

fix: ensure we get mock response when meteringpoing doesnot exists

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Model/EnqueueMissingMeasurementsLogHttpV1.cs

Add initial draft of model for enqueuing missing measurements logs through the `EnqueueActorMessagesHttpClient`, to be used in EDI for the route & model body.
- Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/745
- EDI PR which uses this model: https://github.com/Energinet-DataHub/opengeh-edi/pull/1608

feat: Add enqueue missing measurements log model for BRS-045

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Model/EnqueueMissingMeasurementsLogHttpV1.cs

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/745

fix: Update enqueue missing measurements log

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Model/EnqueueMissingMeasurementsLogHttpV1.cs

Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/745

fix: Update enqueue actor messages for missing measurements log

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Model/EnqueueMissingMeasurementsLogHttpV1.cs

feat: Add idempotency key to brs 045 enqueue message

---

source/ProcessManager.Components/MeteringPointMasterData/MeteringPointMasterDataProvider.cs

Ensure we request a valid metering point id for the performance test to test the performance of the master data provider

test: use correct metering point id to fetch master data

---

source/ProcessManager.Orchestrations/Processes/BRS_021/CapacitySettlementCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ElectricalHeatingCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/NetConsumptionCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs
source/ProcessManager.Orchestrations/Processes/BRS_045/MissingMeasurementsLogOnDemandCalculation/V1/Orchestration/OrchestrationDescriptionBuilder.cs

Removed the "under development" flags for the following orchestrations:
- Missing Measurements Log (and on demand)
- Electricalæ Heating
- Capacity Settlement
- Net Consumption 
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/776

refac: Removed under development flags 

---

source/ProcessManager.Orchestrations.Tests/Unit/Extensions/DependencyInjection/MeasurementsClientExtensionsTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClientTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClient.cs

feat: log execution time to send event to event hub brs021

---

source/ProcessManager.Components/MeteringPointMasterData/MeteringPointMasterDataProvider.cs
source/ProcessManager.Orchestrations.Tests/Unit/Extensions/DependencyInjection/MeasurementsClientExtensionsTests.cs
source/ProcessManager.Orchestrations.Tests/Unit/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClientTests.cs
source/ProcessManager.Orchestrations/Processes/BRS_021/ForwardMeteredData/Measurements/MeasurementsClient.cs

test: mock entire call to get master data to see performance impact

---

docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Abstractions/Processes/BRS_024/V1/Model/RequestYearlyMeasurementsAcceptedV1.cs
source/ProcessManager.Orchestrations/Processes/BRS_024/V1/Activities/EnqueueActorMessagesActivity_Brs_024_V1.cs

feat: added metering point id to RequestYearlyMeasurementsAcceptedV1

---

source/ProcessManager.Orchestrations/Processes/BRS_024/V1/Activities/PerformBusinessValidationActivity_Brs_024_V1.cs
source/ProcessManager.Orchestrations/Processes/BRS_024/V1/Model/RequestYearlyMeasurementsBusinessValidatedDto.cs

Get master data for received at date for business validation. 
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/810

feat: get master data for business validation (brs021)

---

.github/workflows/ci-dotnet-runtests.yml
.github/workflows/processmanager-client-bundle-publish.yml
docs/ProcessManager.Client/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Components.Abstractions/ReleaseNotes/ReleaseNotes.md
docs/ProcessManager.Orchestrations.Abstractions/ReleaseNotes/ReleaseNotes.md
source/ProcessManager.Abstractions/ProcessManager.Abstractions.csproj
source/ProcessManager.Client.Tests/ProcessManager.Client.Tests.csproj
source/ProcessManager.Client/ProcessManager.Client.csproj
source/ProcessManager.Components.Abstractions/ProcessManager.Components.Abstractions.csproj
source/ProcessManager.Components.Tests/ProcessManager.Components.Tests.csproj
source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
source/ProcessManager.Example.Orchestrations.Tests/ProcessManager.Example.Orchestrations.Tests.csproj
source/ProcessManager.Orchestrations.Abstractions/ProcessManager.Orchestrations.Abstractions.csproj
source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
source/ProcessManager.SubsystemTests/ProcessManager.SubsystemTests.csproj
source/ProcessManager.Tests/ProcessManager.Tests.csproj

See title.
Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/680

chore: Use latest TestCommon and Azure Functions Core Tool

---

source/ProcessManager.Orchestrations/host.json

chore: remove unused event hub host settings

---

source/ProcessManager.SubsystemTests/Processes/BRS_021/CapacitySettlementCalculation/V1/CapacitySettlementCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_021/NetConsumptionCalculation/V1/NetConsumptionCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_045/MissingMeasurementsLogCalculation/V1/MissingMeasurementsLogCalculationScenario.cs
source/ProcessManager.SubsystemTests/Processes/BRS_045/MissingMeasurementsLogOnDemand/V1/MissingMeasurementsLogOnDemandCalculationScenario.cs

test: skip subsystem tests which dependes on data

---

source/ProcessManager.Components/MeteringPointMasterData/ConstantAdditionalMeasurementsRecipientsProvider.cs

Load the test values for additional recipients in preprod.
